var a={"name":"Test","age":20,"ispass":true,"subject":{"FSD2":"NAS","FCSP":"TAT"},"marks":[25,23,21],"test":null}
console.log(a)
console.log(a.name)
console.log(a['name'])
console.log(a.age)
console.log(a['age'])
console.log(a.ispass)
console.log(a.subject)
console.log(a.marks)
console.log(a.test)
console.log(a.subject.FSD2)
console.log(a.marks[0])