const d = require('./j1.json')
console.log(d)
console.log(d.name)
console.log(d['name'])
console.log(d.age)
console.log(d['age'])
console.log(d.ispass)
console.log(d.subject)
console.log(d.marks)
console.log(d.test)
console.log(d.subject.FSD2)
console.log(d.marks[0])